# Generated by Django 4.0.5 on 2022-06-20 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comment_comment_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='exposure_finish',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 14, 14, 39, 609934, tzinfo=utc), verbose_name='노출종료일자'),
        ),
        migrations.AddField(
            model_name='article',
            name='exposure_start',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 14, 14, 39, 609934, tzinfo=utc), verbose_name='노출시작일자'),
        ),
    ]
