# Generated by Django 4.0.5 on 2022-06-21 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_exposure_finish_article_exposure_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='exposure_finish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출종료일자'),
        ),
        migrations.AlterField(
            model_name='article',
            name='exposure_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='노출시작일자'),
        ),
    ]
