# Generated by Django 4.0.5 on 2022-06-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_hobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hobby',
            field=models.ManyToManyField(to='user.hobby', verbose_name='취미'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='introduction',
            field=models.TextField(blank=True, null=True, verbose_name='자기소개'),
        ),
    ]
